@extends('app',
    [
        'name'=>'AuthLogin',
        'data'=>[
                'errors'=>$errors->getMessages(),
                'old'=>Session::getOldInput()
            ],
        'auth'=>''
    ]
)
